[book]
authors = ["gahag"]
language = "en"
multilingual = false
src = "src"
title = "Hush"

[output.html]
additional-js = ["theme/hush-highlight.js"]
git-repository-url = "https://github.com/hush-shell/hush"
